example:
  property: "This is default property"

server:
  port: 5555

# Eureka Server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ali5.qixqi.cn:8761/eureka/

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Zuul Server
zuul:
  routes:
    userservice: /user/**
    filesystemservice: /filesystem/**
    authenticationservice: /auth/**
    filesharingservice: /filesharing/**
  ignored-services: "*"
  prefix: /api
  sensitive-headers: Cookie, Set-Cookie   # 配置zuul传播Authorization Header

# Zuul 超时配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2500     # 2.5秒


# 设置日志级别
logging:
  level:
    cn.qixqi.pan: DEBUG

# UserContext
user-context:
  key:
    trace-id: "trace_id"
    auth-token: "auth_token"
    uid: "uid"

# JWT 令牌密钥
jwt:
  signing:
    key: "7f.@$s7232biebs"


spring:
  # Spring Sleuth & Zipkin
  zipkin:
    base-url: http://106.13.37.37:9411
  sleuth:
    sampler:
      probability: 1.0    # 跟踪全部事务