example:
  property: "This is default property"
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

  datasource:
    url: "jdbc:mysql://ping.qixqi.cn:3306/pan?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: "root"
    password: "1214"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
    initialization-mode: never