example:
  property: "This is default property"

server:
  servlet:
    context-path: /auth
  port: 8901

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: "org.hibernate.dialect.MySQL5InnoDBDialect"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  datasource:
    url: "jdbc:mysql://ali.qixqi.cn:3306/pan?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
    username: "root"
    password: "1214"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
    initialization-mode: never
  zipkin:
    base-url: http://shimengya.qixqi.cn:9411
  sleuth:
    sampler:
      probability: 1.0    # 跟踪全部事务

# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ali5.qixqi.cn:8761/eureka/

# JWT 令牌密钥
jwt:
  signing:
    key: "7f.@$s7232biebs"

# 设置日志级别
logging:
  level:
    cn.qixqi.pan: DEBUG

# UserContext
user-context:
  key:
    trace-id: "trace_id"
    auth-token: "auth_token"
    uid: "uid"