example:
  property: "This is default property"
server:
  port: 9000

spring:
  data:
    # mongo3.0 以上，host和port配置不支持，必须使用uri配置所有信息
    mongodb:
      uri: mongodb://pan:pan1214@ali.qixqi.cn:29017,ping.qixqi.cn:29017,ali3.qixqi.cn:29017/pan
  redis:
    cluster:
      nodes: ali.qixqi.cn:6379,ping.qixqi.cn:6379,ali3.qixqi.cn:6379,ali4.qixqi.cn:6379,ali5.qixqi.cn:6379,ali6.qixqi.cn:6379
      max-redirects: 2    # 最大重定向次数
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
    password: redis1214
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0

  # Spring Sleuth & Zipkin
  zipkin:
    base-url: http://106.13.37.37:9411
  sleuth:
    sampler:
      probability: 1.0  # 跟踪全部事务
  cloud:
    # 消息队列配置
    stream:
      bindings:
        inBoundFS:
          destination: testTopic          # 消息队列名称
          content-type: application/json  # 消息类型
          group: filesharingGroup         # 消费者组的名称，保证服务实例中只有一个处理消息
      kafka:
        binder:
          # Kafka 和 ZooKeeper 的地址
          zkNodes: ping.qixqi.cn:2181
          brokers: ping.qixqi.cn:9092
          required-acks: 1


# Eureka 服务发现
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://120.78.133.190:8761/eureka/	# ali5.qixqi.cn


# Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露所有端点
  endpoint:
    shutdown:
      enabled: true     # get请求不行，post可以

# 设置日志级别
logging:
  level:
    cn.qixqi.pan: DEBUG

# 是否初始化 mongodb
# TODO: 初始化时，删除以前的数据
db:
  mongodb:
    rebuild: false
    init:
      file_share: "file_share.json"
      file_share_link: "file_share_link.json"

# UserContext
user-context:
  key:
    trace-id: "trace_id"
    auth-token: "Authorization"
    uid: "uid"

# JWT 令牌密钥
jwt:
  signing:
    key: "7f.@$s7232biebs"